name 'stefanozanella-rsync'
version '0.0.1'
author 'Stefano Zanella'
license 'Apache2'
source 'https://github.com/stefanozanella/puppet-rsync'
summary 'Puppet module for rsync'
description 'This module installs and manages xinetd managed rsync. Check README.rdoc for details. stefanozanella/common module is needed to let catalog compile, but you aren't forced to actually use provided features such as firewall management.'
dependency 'stefanozanella/common', '>=0.0.1'
